// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: optimizator.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OptimizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Function      string                 `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	Tolerance     float64                `protobuf:"fixed64,2,opt,name=tolerance,proto3" json:"tolerance,omitempty"`
	MaxIter       int64                  `protobuf:"varint,3,opt,name=maxIter,proto3" json:"maxIter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationRequest) Reset() {
	*x = OptimizationRequest{}
	mi := &file_optimizator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationRequest) ProtoMessage() {}

func (x *OptimizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_optimizator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationRequest.ProtoReflect.Descriptor instead.
func (*OptimizationRequest) Descriptor() ([]byte, []int) {
	return file_optimizator_proto_rawDescGZIP(), []int{0}
}

func (x *OptimizationRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *OptimizationRequest) GetTolerance() float64 {
	if x != nil {
		return x.Tolerance
	}
	return 0
}

func (x *OptimizationRequest) GetMaxIter() int64 {
	if x != nil {
		return x.MaxIter
	}
	return 0
}

type Variable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_optimizator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_optimizator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_optimizator_proto_rawDescGZIP(), []int{1}
}

func (x *Variable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variable) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type OptimizationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variable      []*Variable            `protobuf:"bytes,1,rep,name=Variable,proto3" json:"Variable,omitempty"`
	FunctionValue float64                `protobuf:"fixed64,2,opt,name=functionValue,proto3" json:"functionValue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizationReply) Reset() {
	*x = OptimizationReply{}
	mi := &file_optimizator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizationReply) ProtoMessage() {}

func (x *OptimizationReply) ProtoReflect() protoreflect.Message {
	mi := &file_optimizator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizationReply.ProtoReflect.Descriptor instead.
func (*OptimizationReply) Descriptor() ([]byte, []int) {
	return file_optimizator_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizationReply) GetVariable() []*Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

func (x *OptimizationReply) GetFunctionValue() float64 {
	if x != nil {
		return x.FunctionValue
	}
	return 0
}

var File_optimizator_proto protoreflect.FileDescriptor

const file_optimizator_proto_rawDesc = "" +
	"\n" +
	"\x11optimizator.proto\x12\foptimization\x1a\x1bgoogle/protobuf/empty.proto\"i\n" +
	"\x13OptimizationRequest\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x1c\n" +
	"\ttolerance\x18\x02 \x01(\x01R\ttolerance\x12\x18\n" +
	"\amaxIter\x18\x03 \x01(\x03R\amaxIter\"4\n" +
	"\bVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"m\n" +
	"\x11OptimizationReply\x122\n" +
	"\bVariable\x18\x01 \x03(\v2\x16.optimization.VariableR\bVariable\x12$\n" +
	"\rfunctionValue\x18\x02 \x01(\x01R\rfunctionValue2\x9e\x01\n" +
	"\fOptimization\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\fOptimization\x12!.optimization.OptimizationRequest\x1a\x1f.optimization.OptimizationReply\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_optimizator_proto_rawDescOnce sync.Once
	file_optimizator_proto_rawDescData []byte
)

func file_optimizator_proto_rawDescGZIP() []byte {
	file_optimizator_proto_rawDescOnce.Do(func() {
		file_optimizator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_optimizator_proto_rawDesc), len(file_optimizator_proto_rawDesc)))
	})
	return file_optimizator_proto_rawDescData
}

var file_optimizator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_optimizator_proto_goTypes = []any{
	(*OptimizationRequest)(nil), // 0: optimization.OptimizationRequest
	(*Variable)(nil),            // 1: optimization.Variable
	(*OptimizationReply)(nil),   // 2: optimization.OptimizationReply
	(*emptypb.Empty)(nil),       // 3: google.protobuf.Empty
}
var file_optimizator_proto_depIdxs = []int32{
	1, // 0: optimization.OptimizationReply.Variable:type_name -> optimization.Variable
	3, // 1: optimization.Optimization.Ping:input_type -> google.protobuf.Empty
	0, // 2: optimization.Optimization.Optimization:input_type -> optimization.OptimizationRequest
	3, // 3: optimization.Optimization.Ping:output_type -> google.protobuf.Empty
	2, // 4: optimization.Optimization.Optimization:output_type -> optimization.OptimizationReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_optimizator_proto_init() }
func file_optimizator_proto_init() {
	if File_optimizator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_optimizator_proto_rawDesc), len(file_optimizator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_optimizator_proto_goTypes,
		DependencyIndexes: file_optimizator_proto_depIdxs,
		MessageInfos:      file_optimizator_proto_msgTypes,
	}.Build()
	File_optimizator_proto = out.File
	file_optimizator_proto_goTypes = nil
	file_optimizator_proto_depIdxs = nil
}
